# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30412413c1c0bdb2fa9b3f99bb06dccac3a30daac8dc99e730ced216d11f4ad2fff0638828c4284273577213c22434f538ea07a1cc38e58b4cc831652531b0c1

test:
  secret_key_base: 770d8c7ccd97abba4206b55bbbca959a62dc5fe832828a307088a433d6060d284c98af0175dc1bd246c8cebd070a284dfdc3377a86eed570a143464ad3a027cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
